import Head from 'next/head'
import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'
import GlobleMenu from '@/components/globalMenu'
import Router from "next/router"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const goTestPage = () => {
    Router.push({
      pathname: "/test/test",
      query: {
        name: "zhangsan",
        age: 22
      }
    })
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link rel="stylesheet" type="text/css" media="screen and (min-width:1200px)" href="@/styles/index1200.css" /> */}
      </Head>
      <main>
        <GlobleMenu />
        <button onClick={goTestPage}>跳转到test页面</button>
      </main>
    </>
  )
}
