import Head from 'next/head'
import GlobleMenu from '@/components/globalMenu'
import { useRouter } from "next/router"
import { Button, Space } from 'antd';


export default function Home() {
  const router = useRouter()

  const goTestPage = () => {
    router.push({
      pathname: "/query/query",
      query: {
        name: "zhangsan",
        age: 22
      }
    })
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <GlobleMenu />
        <Space wrap className='m20'>
          <Button type="primary" onClick={ goTestPage }>跳转到「路由传参」</Button>
        </Space>
      </main>
    </>
  )
}
